# Generated by Django 3.0.6 on 2020-08-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField(default='')),
                ('language', models.TextField(default='')),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='', max_length=500)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('rules', models.CharField(default='', max_length=1500)),
                ('full_rules', models.TextField(default='')),
                ('prizes', models.TextField(default='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('schedule', models.TextField(default='')),
                ('contacts', models.TextField(default='')),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('public', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('official_streamer_twitch', models.URLField(default='')),
                ('official_streamer_youtube', models.URLField(default='')),
                ('partners_streamers_youtube', models.TextField(default='')),
                ('discord_server', models.URLField(default='')),
                ('members_count', models.CharField(default='0', max_length=500)),
                ('type', models.CharField(choices=[('F', 'Free agents'), ('P', 'Pair Registration'), ('T', 'Teams')], default='F', max_length=1)),
                ('formattype', models.CharField(choices=[('S', 'Default format'), ('R', 'Round Robin')], default='S', max_length=1)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partners_streamers_twitch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Balance.Streamers')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch', models.URLField(default='')),
                ('steam', models.URLField(default='')),
                ('youtube', models.URLField(default='')),
                ('discord', models.TextField(default='')),
                ('discord_server', models.URLField(default='')),
                ('discord_server_tournament', models.URLField(default='')),
                ('dark_mode', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, default='no_photo.jpg', upload_to='images/')),
                ('tournaments', models.ManyToManyField(to='Balance.TournamentModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
