# Generated by Django 3.0.6 on 2020-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
