# Generated by Django 3.0.6 on 2020-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='official_streamer_language',
            field=models.TextField(default=''),
        ),
    ]
