# Generated by Django 3.1.2 on 2020-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0002_tournamentmodel_official_streamer_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamers',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('RN', 'Russian+English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='platform',
            field=models.CharField(choices=[('T', 'Twitch'), ('Y', 'Youtube')], default='T', max_length=1),
        ),
    ]
