# Generated by Django 3.0.6 on 2020-07-30 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0002_tournamentmodel_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='end_registration',
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='contacts',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='full_rules',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='prizes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='schedule',
            field=models.TextField(default=''),
        ),
    ]
