# Generated by Django 3.1.2 on 2020-11-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0003_auto_20201108_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='discord_server',
        ),
    ]
