# Generated by Django 3.1.2 on 2020-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0005_userprofile_bg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bg_user',
            field=models.CharField(choices=[('00', 'Default'), ('01', 'Stars'), ('02', 'Cycle'), ('03', 'Ground'), ('04', 'Winter'), ('05', 'Bang'), ('06', 'Cybercity'), ('07', 'Ink')], default='00', max_length=2),
        ),
    ]
